name: Slack Notification on Issue Creation

on:
  issues:
    types:
      - opened

jobs:
  send-slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Send Slack Message
        uses: slackapi/slack-github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          channel: '#your-slack-channel'
          text: "🚨 New issue created: *{{ github.event.issue.html_url }}* \n\n Title: {{ github.event.issue.title }} \n Body: {{ github.event.issue.body }}"
